-- 코드를 입력하세요
SELECT A.CART_ID
FROM (SELECT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME LIKE 'Milk') A,
     (SELECT CART_ID
     FROM CART_PRODUCTS
     WHERE NAME LIKE 'Yogurt') B
WHERE A.CART_ID = B.CART_ID
ORDER BY A.CART_ID