-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS    -- LEFT OUTS
LEFT OUTER JOIN ANIMAL_INS AS INS
ON  OUTS.ANIMAL_ID = INS.ANIMAL_ID  -- 같으면 결과에 나옴, INS가 없어도 나옴
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID
